base/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView


from .views import *

urlpatterns = [
  path('register/',RegisterPage.as_view(), name='register'),
  path('login/',CustomLoginView.as_view(), name='login'),
  path('logut/',LogoutView.as_view(next_page='login'), name='logout'),
  path('',TaskList.as_view(), name='tasks'),
  path('task/<int:pk>',TaskDetail.as_view(), name='detail'),
  path('create-task/',TaskCreate.as_view(), name='create'),
  path('update-task/<int:pk>',TaskUpdate.as_view(), name='update'),
  path('delete-task/<int:pk>',TaskDelete.as_view(), name='delete'),
]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls'))
]

base/models.py
from django.db import models
from django.contrib.auth.models import User

class Task(models.Model):
  user = models.ForeignKey(User,on_delete=models.CASCADE, null=True,blank=True)
  title = models.CharField(max_length=200)
  description = models.TextField(null=True,blank=True)
  complete = models.BooleanField(default=False)
  created = models.DateTimeField(auto_now_add=True)

  def __str__(self):
    return self.title

  class Meta:
    ordering = ['complete']

base/forms.py
from django.forms import ModelForm 
from django import forms 
from .models import *

class TaskForm(ModelForm):
  class Meta:
    model = Task
    fields = '__all__'

base/views.py
from django.shortcuts import redirect, render
from django.views.generic import (
  ListView, 
  DetailView, 
  CreateView,
  UpdateView,
  DeleteView,
  FormView
  )
from django.contrib.auth.views import LoginView
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth  import login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy

from .models import *
#from .forms import *

class CustomLoginView(LoginView):
  template_name='base/login.html'
  fields = '__all__'
  redirect_authenticated_user = True

  def get_success_url(self):
    return reverse_lazy('tasks')


class RegisterPage(FormView):
  model = Task
  form_class = UserCreationForm
  redirect_authenticated_user = True
  success_url = reverse_lazy('tasks')
  template_name = 'base/register.html'

  def form_valid(self, form):
    user = form.save()
    if user is not None:
      login(self.request,user)
    return super(RegisterPage,self).form_valid(form)

  def get(self, request, *args, **kwargs):
    if self.request.user.is_authenticated:
      return redirect('tasks')
    return super(RegisterPage,self).get(request, *args, **kwargs)

class TaskList(LoginRequiredMixin,ListView):
  model=Task
  context_object_name='tasks'

  def get_context_data(self, **kwargs):
    context = super().get_context_data(**kwargs)
    context['tasks'] = context['tasks'].filter(user=self.request.user)
    context['count'] = context['tasks'].filter(complete=False).count()

    search_input = self.request.GET.get('search-area') or ''
    if search_input:
      context['tasks'] = context['tasks'].filter(title__startswith=search_input)
    
    context['search_input'] = search_input
    return context

class TaskDetail(LoginRequiredMixin,DetailView):
  model=Task

class TaskCreate(LoginRequiredMixin,CreateView):
  """ form_class=TaskForm
  template_name='base/task_form.html' """
  model=Task
  fields = ('title','description','complete')
  success_url = reverse_lazy('tasks')

  def form_valid(self, form):
    form.instance.user = self.request.user
    return super(TaskCreate,self).form_valid(form)

class TaskUpdate(LoginRequiredMixin,UpdateView):
  model=Task
  fields = ('title','description','complete')
  success_url = reverse_lazy('tasks')

class TaskDelete(LoginRequiredMixin,DeleteView):
  model = Task
  context_object_name='task'
  success_url = reverse_lazy('tasks')

base/templates/base/login.html
{% extends "base/main.html" %}

{% block head %}
    <h2 class="text-center">Login</h2>
{% endblock %}
{% block body %}
    <form method="POST" class="mb-3">
      {% csrf_token %}
      <div class="mb-3">
        <label for="id_username" class="form-label">{{form.username.label_tag}}</label>
        <input type="text" class="form-control" required id="id_username" name="{{form.username.name}}">
      </div>
      <div class="mb-3">
        <label for="id_password" class="form-label">Password</label>
        <input type="password" class="form-control" required id="id_password" name="{{form.password.name}}">
      </div>
      <button type="submit" class="btn btn-primary">Submit</button>
    </form>
      <p>Don't have an account? <a href="{% url 'register' %}">Register</a></p>
{% endblock %}

base/templates/base/main.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
  <link rel="stylesheet" href="https://bootswatch.com/5/lumen/bootstrap.min.css">
  <title>To Do Items</title>
</head>
<body class="bg-active">
  <div class="container mt-5 col-md-5">
    <div class="card">
      <div class="card-header bg-info">
        {% block head %}

        {% endblock %}
      </div>
      <div class="card-body bg-secondary">
        {% block body %}

        {% endblock %}
      </div>
    </div>
  </div>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js" integrity="sha384-W8fXfP3gkOKtndU4JGtKDvXbO53Wy8SZCQHczT5FMiiqmQfUpWbYdTil/SxwZgAN" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.min.js" integrity="sha384-skAcpIdS7UcVUC05LJ9Dxay8AXcDYfBJqt1CJ85S/CFujBsIzCIv+l9liuYLaMQ/" crossorigin="anonymous"></script>
</body>
</html>

base/templates/base/register.html
{% extends "base/main.html" %}

{% block head %}
    <h2 class="text-center">Register</h2>
{% endblock %}
{% block body %}
    <form method="POST" class="mb-3">
      {% csrf_token %}
      <div class="mb-3">
        <label for="id_username" class="form-label">{{form.username.label_tag}}</label>
        <input type="text" class="form-control" required  autofocus autocapitalize="none" autocomplete="username"  id="id_username" name="{{form.username.name}}">
      </div>
      <div class="mb-3">
        <label for="id_password1" class="form-label">{{form.password1.label_tag}}</label>
        <input type="password" autocomplete="new-password" class="form-control" required id="id_password1" name="{{form.password1.name}}">
      </div>
      <div class="mb-3">
        <label for="id_password2" class="form-label">{{form.password2.label_tag}}</label>
        <input type="password" autocomplete="new-password" class="form-control" required id="id_password2" name="{{form.password2.name}}">
      </div>
      <button type="submit" class="btn btn-primary">Register</button>
    </form>
      <p>Alredy have an account? <a href="{% url 'login' %}">Login</a></p>
{% endblock %}

base/templates/base/task_confirm_delete.html
{% extends "base/main.html" %} {% block head %}
<div class="ms-2 me-auto">
  <a href="{% url 'tasks' %}" class="btn btn-outline-light pt-1"
    ><span class="text-dark">Cancel</span></a
  >
</div>
{% endblock %} {% block body %}
<div class="d-flex justify-content-between align-items-center">
  <div class="ms-2 me-auto">
    <h3>
      Confirm delete <strong><i>{{task}}</i></strong>
    </h3>
  </div>
  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Delete" class="btn btn-danger" />
  </form>
</div>
{% endblock %}

base/templates/base/task_detail.html
{% extends "base/main.html" %}

{% block content %}
<h1>Content</h1>
<a href="{% url 'tasks' %}">Go back</a>

<h3>{{task.title}}</h3>
<ul>
  <li>{{task.description}}</li>
  <li>{{task.created}}</li>
</ul>
{% endblock %}

base/templates/base/task_form.html
{% extends "base/main.html" %}

{% block head %}
    <div class="ms-2 me-auto">
      <a href="{% url 'tasks' %}" class="btn btn-outline-light pt-1"><span class="text-dark">Back</span></a>
    </div>
{% endblock %}
{% block body %}
    <form method="POST">
      {% csrf_token %}
      <div class="mb-3">
        <label for="id_title" class="form-label">{{ form.title.label_tag }}</label>
        <input type="text" class="form-control" id="id_title" value="{% if form.description.value %}{{form.title.value}}{%endif%}" name="{{form.title.name}}">
      </div>
      <div class="mb-3">
        <label for="id_description" class="form-label">{{ form.description.label_tag }}</label><br>
        <textarea class="form-control" id="id_description" name="{{form.description.name}}">{% if form.description.value %} {{form.description.value}} {%endif%}</textarea>
      </div>
      <div class="mb-3 form-check">
        <input type="checkbox" class="form-check-input" id="id_complete" name="{{ form.complete.name }}" {% if form.complete.value %} checked {% endif %}>
        <label class="form-check-label" for="id_complete">{{ form.complete.label }}</label>
      </div>
      <button type="submit" class="btn btn-primary">Submit</button>
    </form>
{% endblock %}

base/templates/base/task_list.html
{% extends "base/main.html" %}

{% block head %}
    <div class="d-flex justify-content-between align-items-center">
      <div class="ms-2 me-auto">
        <h1 class="card-title">Hello, {{ request.user|title }}</h1>
        <h6 class="card-subtitle mb-2 text-secondary">You have <i>{{count}}</i> incomplete task{{ count|pluralize:"s"}} </h6>
      </div>
      {% if request.user.is_authenticated %}
        <a href="{% url 'logout' %}" class="btn btn-outline-light text-dark">Logout</a>
      {% else %}
        <a href="{% url 'login' %}">Login</a>
      {% endif %}
    </div>
  {% endblock %}
  {% block body %}
    <div class="d-flex justify-content-between align-items-center mb-4">
      <form action="" method="GET" style="width: 60%;" class="d-flex justify-content-between align-items-center">
        <input class="form-control" style="width: 69%;" type="search" placeholder="Search task" name="search-area" value="{{search_input}}">
        <input class="btn btn-outline-primary pt-1" type="submit" value="search"></input>
      </form>
      <a href="{% url 'create' %}" class="btn btn-primary">&#43;</a>
    </div>
    <div>
      <ul class="list-group ">
        {% for task in tasks %}
          <li class="list-group-item d-flex justify-content-between align-items-center">
            <div class="ms-2 me-auto">
              {% if task.complete %}
                <div class="fw-bold"><s><span>&#10004;</span> {{task}}</s></div>
              {% else %}
                <div class="fw-bold"><span>&#10004;</span> {{task}}</div>
              {% endif%}
            </div>
            <div>
              <a href="{% url 'update' task.id %}" class="btn btn-warning">&#9998;</a>
              <a href="{% url 'delete' task.id %}" class="btn btn-danger">&#10799;</a>
            </div>
          </li>
          {% empty %}
          <h3>there are not tasks</h3>
          {% endfor %}
        </ul>
    </div>
{% endblock %}